package com.spring.boot.springrepository.Model;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.Check;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Check(constraints = "role = 'user' or role = 'admin'")
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    // it will be autogenerated so it will never be null
    private Integer id;

    @NotEmpty(message = "name must not be empty")
    @Size(min = 5, message = "name must not be less than 5 characters")
    @Column(columnDefinition = "varchar(30) not null")
    private String name;

    @NotEmpty(message = "userName must not be empty")
    @Size(min = 5, message = "userName must not be less than 5 characters")
    @Column(columnDefinition = "varchar(30) unique not null")
    private String userName;

    @NotEmpty(message = "password must not be empty")
    @Column(columnDefinition = "varchar(30) not null")
    private String password;

    @Email(message = "Email must be valid")
    @NotEmpty(message = "email must not be empty")
    @Column(columnDefinition = "varchar(30) unique not null")
    private String email;

    @NotEmpty(message = "role must not be empty")
    @Pattern(regexp = "^(user|admin)$", message = "role must be either user or admin")
    @Column(columnDefinition = "varchar(6) not null")
    private String role;

    @NotNull(message = "age must not be empty")
    @Positive(message = "age must be a positive number")
    @Column(columnDefinition = "int not null")
    private Integer age;
}
